### ISSUE TITLE
`parseForESLint` return type doesn't unify with `@types/eslint`'s `ParserModule`

### ISSUE THREAD

**Issue by cprussin** [ota-meshi/jsonc-eslint-parser#159]
As the issue title suggests, the [`parseForESLint` return type](https://github.com/ota-meshi/jsonc-eslint-parser/blob/master/src/parser/parser.ts#L22-L27) doesn't unify with the one in [DefinitlyTyped's implementation of `@types/eslint`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts#L900-L905).  Specifically the message I'm seeing is this:

```
src/index.ts:123:24 - error TS2322: Type 'typeof import("/home/cprussin/Projects/@cprussin/node_modules/.pnpm/jsonc-eslint-parser@2.2.0/node_modules/jsonc-eslint-parser/lib/index")' is not assignable to type 'ParserModule | undefined'.
  Type 'typeof import("/home/cprussin/Projects/@cprussin/node_modules/.pnpm/jsonc-eslint-parser@2.2.0/node_modules/jsonc-eslint-parser/lib/index")' is not assignable to type '{ parseForESLint(text: string, options?: any): ESLintParseResult; }'.
    The types of 'parseForESLint(...).ast' are incompatible between these types.
      Property 'sourceType' is missing in type 'JSONProgram' but required in type 'Program'.

123     languageOptions: { parser: jsonParser },
                           ~~~~~~

  ../../node_modules/.pnpm/@types+estree@1.0.1/node_modules/@types/estree/index.d.ts:85:5
    85     sourceType: 'script' | 'module';
           ~~~~~~~~~~
    'sourceType' is declared here.
```

Could be some version drift between this library and the types in DefinitelyTyped, or could be some difference caused by me using the flat config format, I haven't yet investigated.  However based on the types I don't think it is, I think that [this library's `JSONProgram` type](https://github.com/ota-meshi/jsonc-eslint-parser/blob/master/src/parser/ast.ts#L32-L38) probably should be extending the [ESTree `Program` type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/estree/index.d.ts#L83-L88) (I'm no expert though so that may be nonsense).

**Comment by cprussin** [comment]
@ota-meshi I'm happy to submit a PR for this one but as I'm no expert I'll need advice on the correct fix here.

**Comment by ota-meshi** [comment]
I think the eslint type definition is wrong.  Actually eslint accepts anything other than estree.

**Comment by cprussin** [comment]
understood, I can put a PR in over there. Thanks!

**Comment by cprussin** [comment]
@ota-meshi do you know if the AST specification is documented anywhere?  The best I could find is https://eslint.org/docs/latest/extend/custom-parsers#ast-specification which would seem to support that it is in fact required that the AST extends the ESTree type.  Is there some other spec somewhere that says otherwise that I can use to construct a PR to fix the eslint definition?

**Comment by ota-meshi** [comment]
There are no specs, but there are RFCs.
https://github.com/eslint/rfcs/tree/main/designs/2020-generic-ast-support
https://github.com/eslint/rfcs/tree/main/designs/2022-languages
