### ISSUE TITLE
Docs: Document usage with flat config in README.md?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ota-meshi/jsonc-eslint-parser#203]
Looks like this parser is still supported well in [flat config files](https://eslint.org/docs/latest/use/configure/configuration-files-new). Would you be open to a PR adding a description of how to use it in the README.md?

Trimmed-down example:

```js
export default [
  {
    files: ["*.json", "*.json5"],
    languageOptions: {
      parser: jsoncParser,
    }
  },
];

```

**Comment by JounQin** [comment]
PR is always welcome.
