### ISSUE TITLE
Node engine regression

### ISSUE THREAD

**Issue by Badisi** [ota-meshi/jsonc-eslint-parser#86]
### Issue
The upgrade of `eslint-visitor-keys` to `v3` had an impact to your package's required node engine version.

> error eslint-visitor-keys@3.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "10.0.0"
> error Found incompatible module.

### Explanation
`eslint-visitor-keys@v3` now requires : "node": "^12.22.0 || ^14.17.0 || >=16.0.0"
https://github.com/eslint/eslint-visitor-keys/blob/main/package.json#L22

Which makes your package no more compatible with `node < 12.22.0`
https://github.com/ota-meshi/jsonc-eslint-parser/blob/master/package.json#L10

**Comment by ota-meshi** [comment]
You can also use eslint-visitor-keys v1.3.0. So I think it's compatible with node v8, am I misunderstanding?

https://github.com/ota-meshi/jsonc-eslint-parser/blob/master/package.json#L74

**Comment by ota-meshi** [comment]
Thank you for information.
I was expecting the modules that depend on the ESLint you are using to be used.
I found that it didn't work as expected, so I need to downgrade the dependencies.
